DROP EMPLOYEE DATABASE IF EXISTS;
CREATE EMPLOYEE DATABASE IF NOT EXISTS;

USE  EMPLOYEE DATABASE;

CREATE TABLE department ( 
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL
);
CREATE TABLE role(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title: VARCHAR(30) NOT NULL
salary DECIMAL NOT NULL, 
department_if INT
);
CREATE TABLE employee();
